### ISSUE TITLE
Patch version bump breaking deploys

### ISSUE THREAD

**Issue by offero** [bojand/promisify-call#1]
You made a breaking change in a patch bump and now all of our deploys are failing. You changed to ONLY support node 6. That's a BREAKING change, not a patch level bump.

1) What version of the module is the issue happening on? Does the issue happen on latest version?
2.0.2

2) What platform and Node.js version? (For example Node.js 0.12 on Mac OS X)
4.x

3) Sample source code or steps to reproduce
npm install

**Comment by bojand** [comment]
Hello... sorry for any breakage... 

Did `promisify-call@2.0.0` or `@2.0.1` ever work for you under 4.x? I wouldn't expect so...?

I think there are a couple of things:

The initial version of 2.0.0 was published incorrectly stating that it supports 4.x. The `README` is still wrong and I didn't notice it, and I will address that. The fact is with the change in 2.0.0 technically requires LTS to run as it depends on the support of the rest parameter operator (`... arg`). Without using `--harmony` flag when running version 2.x (2.0.0, 2.0.1, and 2.0.2) of this module using node 4.x (at least with 4.6.2, older versions are a gamble) it will not work properly. So I changed the "engines" in `2.0.2` version to properly reflect that. 

I should note that changing the "engines" property of `package.json` should not have any effect on your builds / npm install as `npm` does not fail on those but just reports a warning:

```sh
$ nvm use 4
Now using node v4.6.0 (npm v2.15.9)
$ npm i promisify-call
npm WARN engine promisify-call@2.0.2: wanted: {"node":">=6.9"} (current: {"node":"4.6.0","npm":"2.15.9"})
promisify-call@2.0.2 node_modules/promisify-call
└── with-callback@1.0.2
$
```

So I believe the actual issue is at runtime, and the fact that promisify-call@2.x does not support 4.x without `--harmony` flag. The version bump from 1.0 to 2.0 properly reflects the breakage... The initial publish and documentation of 2.0.0 was incorrect in the respect the engines was incorrect and the README was incorrect. So I fixed the engines (which is not a build failure anyway). I will address the README. 

My suggestion is using 1.x of this module until you update to LTS (which I highly recommend), as it is not recommended to use harmony in production code.

To me it seems 2.x should have never worked with 4.x and it was incorrectly published initially specifying that it could. Change from 2.0.1 => 2.0.2 should not have actually changed much. 

Sorry for any inconvenience.

**Comment by offero** [comment]
Ok, I see. We were actually using this package as a dependency of the mailgun package and some version bump ended up causing a breaking change through that.

Thanks for the clarification. Sorry for the wtf.

**Comment by bojand** [comment]
The `mailgun-js` package? I am the author of that too, and yes there was a bump from 0.7.x => 0.8.0 there... That also was changed to only support LTS. Note that in versions under < 1.0.0, a version change in "minor" spot usually indicates breakage. This is done more as a convenience by most authors, and the spec does not require it. I would stick with 0.7.x there too if you're using Node 4. You can use `"mailgun-js": "~0.7.0"` to safely get < 0.8.0, as the default "^" used by `--save` can be somewhat dangerous. Please see point # 8 [here](https://nodesource.com/blog/eleven-npm-tricks-that-will-knock-your-wombat-socks-off)
