### ISSUE TITLE
Why did you switch from native promises instead of bluebird?

### ISSUE THREAD

**Issue by c3s4r** [bojand/promisify-call#4]
According to this post, bluebird promises are faster than native promises: http://softwareengineering.stackexchange.com/questions/278778/why-are-native-es6-promises-slower-and-more-memory-intensive-than-bluebird

Is there any specific reason to stop using bluebird?

**Comment by bojand** [comment]
I want the library to be Promise implementation agnostic, and therefore default to native promises. I do not see a reason to lock in or add additional dependencies to such a simple module. Native implementation has seen some performance improvements over the releases, and I believe that will continue as well.  Usually there are bigger performance bottlenecks in real world applications anyway, but I do appreciate the fact that every tick counts. Having said that, 1.x uses bluebird, and otherwise it's easy to make the current version use bluebird as well if you don't mind overriding the native global (which bluebird would do anyway):

```js
Promise = require('bluebird')
const promisifyCall = require('promisify-call')

function _uppercase(param, fn) {
  setTimeout(() => {
    return fn(null, param.toUpperCase());
  }, 50);
}
 
function uppercase(param, fn) {
  return promisifyCall(this, _uppercase, ...arguments);
}
 
// now we can call it using callback-style 
uppercase('foo', (err, res) => {
  console.log(res); // FOO 
});
 
// OR promise style 
const res = uppercase('bar');
console.log(res); // Bluebird promise
res.then(s => console.log(s));
```
